### ISSUE TITLE
do you mind to add "yc" (yandex cloud cli) to image ?

### ISSUE THREAD

**Issue by chipitsine** [devops-infra/docker-terragrunt#1001]
if there's no objection, I can work on that.

**Comment by ChristophShyper** [comment]
Hi. Sure, it can be added. I even have Yandex at work, but never accessed it via CLI.

**Comment by chipitsine** [comment]
agreed. I'll prepare pull request.

(it will take some time, I'm not sure whether "yc" is available for arm64)

**Comment by ChristophShyper** [comment]
@chipitsine Added to the current release.
