### ISSUE TITLE
Adding a basic editor to the image

### ISSUE THREAD

**Issue by uptickmetachu** [devops-infra/docker-terragrunt#1156]
## :memo:  Brief description
Would this repo consider adding a simple editor like nano? 

The use case is I want to edit a secrets file using sops from within the container.

**Comment by ChristophShyper** [comment]
Hello.
Sure thing, I'm adding `vim` right now. 
Sorry for missing it, I wasn't editing any files inside the container. Only mounting local files.
But I see how this can be useful.
Will be available in the most current images today.
