### ISSUE TITLE
ARM64 builds not working properly

### ISSUE THREAD

**Issue by adrianjarc** [devops-infra/docker-terragrunt#1268]
## :memo:  Brief description

When trying to run this image on MacBook with M1/M2 processors, AWS CLI doesn't work. You get the error: `Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory`

Issue stems from Dockerfile having default `TARGETPLATFORM` argument set to: `linux/amd64` and not getting an override to also build `arm64` image. 

Could you fix your build scripts to actually build for both platforms?

## :warning: Checklist
* [X] Provided a clear and concise description of what the issue is.
* [X] Given a clear and concise description of what is expected.
* [X] Proposed a clear and concise description of any alternative solutions or other features.
* [ ] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ChristophShyper** [comment]
Hello. I'll have a look into it. I didn't have M2 when I made those changes and didn't have time yet to debug all the changes.
But besides that, there is still a problem with a bunch of Terraform providers not having `arm64` counterparts.
I'm using `--platform linux/amd64` in my `docker run` to make it all work at the moment.

**Comment by adrianjarc** [comment]
> I'm using `--platform linux/amd64` in my `docker run` to make it all work at the moment.

Hello thanks for quick answer. We have updated the image from `devopsinfra/docker-terragrunt:aws-tf-1.2.5-tg-0.38.5` to `devopsinfra/docker-terragrunt:aws-tf-1.3.3-tg-0.39.2` and added platform, and it worked. Would still be better for it to work without this workaround, but for now it is good.

**Comment by ChristophShyper** [comment]
I'll have a look at it for sure. It's in my private backlog for some time already.

**Comment by ChristophShyper** [comment]
> Issue stems from Dockerfile having default TARGETPLATFORM argument set to: linux/amd64 and not getting an override to also build arm64 image.

BTW, @adrianjarc  `TARGETPLATFORM` is set by buildx when running `docker buildx build --platform linux/amd64,linux/arm64`.

**Comment by adrianjarc** [comment]
> Hello. I finally had some time to test it on my M2. The reason was using a base image of the wrong platform. Docker uses the host platform as default, and not the build platform. Why? Who knows... I've fixed it in #1305 It will be published tomorrow in the newest image, after I test it a little bit more. You can test using `test-...` images, e.g. `test-aws-gcp-tf-1.3.5-tg-0.40.2`.

Hello,

since we didn't have time till today, we have tested on an already published image and can confirm it works without the platform workaround.

Closing this issue as it seems resolved.
