### ISSUE TITLE
Terragrunt not working as expected

### ISSUE THREAD

**Issue by karthikprabhut** [devops-infra/docker-terragrunt#1362]
Hello,

I am using this docker image (docker-terragrunt:aws-tf-1.1.7-tg-0.36.6) for my Jenkins pipeline to execute IAC through Terragrunt. When i execute the aws sts its showing me expected output

+ aws sts get-caller-identity
{
    "UserId": "XXXXXXXXXXXXXXXXXXXXx",
    "Account": "999999999999999",
    "Arn": "arn:aws:iam::99999999999999:user/testuser"
}

When am trying the same credentials using "terragrunt plan" am getting below error.

[Pipeline] sh
+ terragrunt plan
time=2022-12-21T21:45:26Z level=error msg=Error finding AWS credentials (did you set the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables?): NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
time=2022-12-21T21:45:26Z level=error msg=Unable to determine underlying exit code, so Terragrunt will exit with error code 1

Is there any option specific to terragrunt ? Kindly advise.

**Comment by ChristophShyper** [comment]
Hello,
Are you running `aws sts get-caller-identity` inside the Docker container?
How are you running the container for Terragrunt? How are you passing AWS credentials?

**Comment by karthikprabhut** [comment]
Hi @ChristophShyper 

Yes am running the execution inside the docker container. Please find my arguments below.

		stage('Build') {
      agent {
        docker {
          reuseNode true
          image 'devopsinfra/docker-terragrunt:aws-tf-1.1.7-tg-0.36.6'
          args "-u root -e 'USER=root' -e 'HOME=/root' -e NO_PROXY --entrypoint=''"
        }
      }
      steps {
        dir ('xxxxxx/xxxxxx/xxxxxx/eks/managed-nodes/core'){
          withAWS(credentials: 'testuseraws'){
            ansiColor('xterm') {
              sh "aws sts get-caller-identity"
              sh "terragrunt plan "

**Comment by ChristophShyper** [comment]
And how is your AWS provider in Terraform configured?

**Comment by karthikprabhut** [comment]
I got it. If i have my architecture like below my provider is defined in parent file terragrunt.hcl. And each child file having related configurations which will look on the parent file for the provider details. Assume currently am trying to execute terragrunt plan in on of the child folder. In this case, how should i pass the variable to look on the parent file to fetch the provider. Thanks in advance.

└── live
    ├── terragrunt.hcl
    ├── prod
    │   ├── app
    │   │   └── terragrunt.hcl
    │   └── vpc
    │       └── terragrunt.hcl
    ├── qa
    │   ├── app
    │   │   └── terragrunt.hcl
    │   └── vpc
    │       └── terragrunt.hcl

**Comment by ChristophShyper** [comment]
How are your AWS credentials passed? As env vars, creds files?

**Comment by karthikprabhut** [comment]
Thanks @ChristophShyper. Right now the credentials are passed from local credential file ~/.aws/credentials. My approach at the moment to make the process in a pipeline. In this case i need to pass the credentials through vars.

**Comment by ChristophShyper** [comment]
If they are passed as a file make sure you mount it for the container. Which is not the case from what I see.
I haven't used Jenkins in many years, so I'm just not sure how it handles all that.
Is `withAWS` setting env vars? Maybe it's just missing region?

**Comment by ChristophShyper** [comment]
@karthikprabhut Any update on your issue?

**Comment by karthikprabhut** [comment]
@ChristophShyper  sorry i forget to update. Its working now. I have mentioned in pipeline like below

withAWS(credentials: 'XXXXXX', region: 'XXXX, role: 'XXXXX')

**Comment by ChristophShyper** [comment]
Great that you managed to fix it :)
