### ISSUE TITLE
please provide Image for TF 1.3.10

### ISSUE THREAD

**Issue by gerhard-strauss-jambit** [devops-infra/docker-terragrunt#1839]
## :memo:  Please provide for Image TF 1.3.10

we currently cant update our deploy Pipeline, since we rely on the TF Plugin Cache. but now we are hit by this Bug and need the newest TF 1.3.10 Version to workaround this Problem.
https://github.com/hashicorp/terraform/issues/34014#issuecomment-1751683477

**Comment by ChristophShyper** [comment]
Hello @gerhard-strauss-jambit !
I've created images for [tf-1.3.10](https://hub.docker.com/repository/docker/devopsinfra/docker-terragrunt/tags?page=1&ordering=last_updated&name=tf-1.3.10) just for you.

**Comment by gerhard-strauss-jambit** [comment]
awesome, thank you 😄
