### ISSUE TITLE
gcloud is missing in $PATH

### ISSUE THREAD

**Issue by assertnotnull** [devops-infra/docker-terragrunt#1974]
## :memo:  Brief description
In the gcp-tf-1.7.0-tg-0.54.21 image the gcloud binary is no the in the $PATH so I have to use the full path to run it.

**Comment by mehdicopter** [comment]
hello,
same in `gcp-tf-1.7.3-tg-0.55.2`

**Comment by ChristophShyper** [comment]
Hello,
Sorry for the late answer, but I'm swamped at work :/
Proper `gcloud` install works only for root user, but when I was adding it long ago it should've worked for other users as well. Maybe they changed something in the meantime. Sorry for not noticing it before.
I'm adding it now to `/etc/bash.bashrc` together with prompt completition.
