### ISSUE TITLE
Add support for OpenTofu instead of Terraform 

### ISSUE THREAD

**Issue by ptpu** [devops-infra/docker-terragrunt#2065]
## :memo:  Brief description

Hey, since Terragrunt version 0.52.0 makes it possible to use OpenTofu instead of Terraform, it would be important to include OpenTofu as an alternative in this Docker container.

https://github.com/gruntwork-io/terragrunt/issues/2690

## :warning: Checklist
* [X] Provided a clear and concise description of what the issue is.
* [X] Given a clear and concise description of what is expected.
* [X] Proposed a clear and concise description of any alternative solutions or other features.
* [X] Added any other context or screenshots about the feature request.
* [X] Associated pull request has been already created and link was provided.

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ChristophShyper** [comment]
Hello, I've added it to the newest release https://github.com/devops-infra/docker-terragrunt/releases/tag/tf-1.7.5-tg-0.55.20

**Comment by kvendingoldo** [comment]
At this moment if you need to have a support of Terraform as well as OpenTofu (and Terragrunt :) ) in one tool you can use https://github.com/tofuutils/tenv which my team wrote some months ago. A lot of users switched to that tool to unify version management in the world of Terraform. 

You're welcome to open any issues or contribute to [tenv](https://github.com/tofuutils/tenv).

**Comment by ChristophShyper** [comment]
@kvendingoldo I had a look at `tenv` but works in a completely different way than expected here. It's more for local environments, not remote ones.
