### ISSUE TITLE
 "gcloud": executable file not found in $PATH: unknown

### ISSUE THREAD

**Issue by nguyen-vo** [devops-infra/docker-terragrunt#2099]
## :memo:  Brief description
I have seen a few issues in the past regarding gcloud $PATH not found or gcloud command not found. 
I tried the latest version of gcp-latest, but still see the same issue.

I tried the following 
```
docker run --rm --user $(id -u):$(id -g) --volume $(pwd):/data \
   -e GOOGLE_APPLICATION_CREDENTIALS=/tmp/keys/adc.json \
   -v $HOME/.config/gcloud/application_default_credentials.json:/tmp/keys/adc.json:ro  \
   --tty --interactive devopsinfra/docker-terragrunt:gcp-latest gcloud --version
```

I am expecting to able to use `gcloud` command

## :warning: Checklist
* [x] Provided a clear and concise description of what the issue is.
* [x] Given a clear and concise description of what is expected.
* [ ] Proposed a clear and concise description of any alternative solutions or other features.
* [x] Added any other context or screenshots about the feature request.
* [x] Associated pull request has been already created and link was provided.
Link to previous PR
- https://github.com/devops-infra/docker-terragrunt/issues/509
- https://github.com/devops-infra/docker-terragrunt/issues/1974

*Check [CONTRIBUTING.md][contributing] and [CODE_OF_CONDUCT.md][code] for more information*

[contributing]: https://github.com/devops-infra/.github/blob/master/CONTRIBUTING.md
[code]: https://github.com/devops-infra/.github/blob/master/CODE_OF_CONDUCT.md

**Comment by ChristophShyper** [comment]
You're right, sorry for that. I tested only via bash.
Inside Docker it can be expanded in a different way when running binaries directly. According to https://stackoverflow.com/questions/28722548/updating-path-environment-variable-permanently-in-docker-container#:~:text=1.%20The%20correct%20answer
So I've added it also as `ENV` and it works now.

**Comment by nguyen-vo** [comment]
Thanks @ChristophShyper for taking a look.

When should we expect a new version for this update?

**Comment by nguyen-vo** [comment]
Ah nevermind I saw the new versions are published 5 hours ago!!

Very appreciated!!
