### ISSUE TITLE
terragrunt prefers opentofu over terraform

### ISSUE THREAD

**Issue by nejec** [devops-infra/docker-terragrunt#2138]
After the upgrade from `docker-terragrunt:aws-tf-1.7.4-tg-0.55.10` to `docker-terragrunt:aws-tf-1.8.2-tg-0.58.2` all providers references in the terraform state file went from `registry.terraform.io` to `registry.opentofu.io`, which is caused because `terragrunt` is using `tofu` instead of `terraform`.

```console
$ terragrunt terragrunt-info
{
  "ConfigPath": "/data/terragrunt.hcl",
  "DownloadDir": "/data/.terragrunt-cache",
  "IamRole": "",
  "TerraformBinary": "tofu",
  "TerraformCommand": "terragrunt-info",
  "WorkingDir": "/data"
}
```

Currently, the image name itself is deceiving that it is primarily `terraform` based but behind the scenes it is actually using `tofu` binary.

Even this is probably not intentional, i suggest splitting images into `terraform` and `opentofu` versions.

**Comment by ChristophShyper** [comment]
Hello! Thanks for pointing that out. In my daily work I use slightly modified version of this module and it uses terraform.
I was not aware terragrunt switches to opentofu. Will have a look at it.

**Comment by ChristophShyper** [comment]
I've just added separate versioning for OpenTofu with release https://github.com/devops-infra/docker-terragrunt/releases/tag/tf-1.8.3-ot-1.7.0-tg-0.58.3. So the two binaries don't need to fight :)
It can be used `devopsinfra/docker-terragrunt:tf-1.8.3-tg-0.58.3` for Terraform.
And `devopsinfra/docker-terragrunt:ot-1.7.0-tg-0.58.3` for OpenTofu.

**Comment by nejec** [comment]
![insertgif.com](https://media0.giphy.com/media/10avZ0rqdGFyfu/200.gif)
