### ISSUE TITLE
image isn't compatible with circleci checkout command after aws-tf-0.14.6-tg-0.28.4

### ISSUE THREAD

**Issue by ideasculptor** [devops-infra/docker-terragrunt#230]
git checkouts no longer work in this repo when using aws-tf-0.14.6-tg.28.5 or better.  It fails to use ssh to checkout git repos despite the presence of this command as part of the checkout step:

```
git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
```

I get the following error:
```
Cloning into '.'...
Username for 'https://github.com': fatal: could not read Username for 'https://github.com': No error information

exit status 128
```

If I back up to the previous version: `aws-tf-0.14.6-tg-0.28.4` or any other earlier version, it works just fine.  The broken-ness continues all the way up to the most recent version.  I was hoping to diff the Dockerfile from one version to the next, but the github repo offers no tags or other notes that would allow me to associate a particular commit with a given tag in dockerhub.

The full text of the circleci checkout command is as follows, but some of the env vars are intentionally obfuscated and unavailable to me.  For this reason, I can't even run a modified version of the command which would provide more debug info.

```
#!/bin/sh
set -e

# Workaround old docker images with incorrect $HOME
# check https://github.com/docker/docker/issues/2968 for details
if [ "${HOME}" = "/" ]
then
  export HOME=$(getent passwd $(id -un) | cut -d: -f6)
fi

echo "Using SSH Config Dir '$SSH_CONFIG_DIR'"
git --version 

mkdir -p "$SSH_CONFIG_DIR"
chmod 0700 "$SSH_CONFIG_DIR"

printf "%s" 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
bitbucket.org ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAubiN81eDcafrgMeLzaFPsw2kNvEcqTKl/VqLat/MaB33pZy0y3rJZtnqwR2qOOvbwKZYKiEO1O6VqNEBxKvJJelCq0dTXWT5pbO2gDXC6h6QDXCaHo6pOHGPUy+YBaGQRGuSusMEASYiWunYN0vCAI8QaXnWMXNMdFP3jHAJH0eDsoiGnLPBlBp4TNm6rYI74nMzgz3B9IikW4WVK+dc8KZJZWYjAuORU3jc1c/NPskD2ASinf8v3xnfXeukU0sJ5N6m5E8VLjObPEO+mN2t/FZTMZLiFqPWc/ALSqnMnnhwrNi2rbfg/rd/IpL8Le3pSBne8+seeFVBoGqzHM9yXw==
' >> "$SSH_CONFIG_DIR/known_hosts"
chmod 0600 "$SSH_CONFIG_DIR/known_hosts"

rm -f "$SSH_CONFIG_DIR/id_rsa"
printf "%s" "$CHECKOUT_KEY" > "$SSH_CONFIG_DIR/id_rsa"
chmod 0600 "$SSH_CONFIG_DIR/id_rsa"
if (: "${CHECKOUT_KEY_PUBLIC?}") 2>/dev/null; then
  rm -f "$SSH_CONFIG_DIR/id_rsa.pub"
  printf "%s" "$CHECKOUT_KEY_PUBLIC" > "$SSH_CONFIG_DIR/id_rsa.pub"
fi

export GIT_SSH_COMMAND='ssh -i "$SSH_CONFIG_DIR/id_rsa" -o UserKnownHostsFile="$SSH_CONFIG_DIR/known_hosts"'

# use git+ssh instead of https
git config --global url."ssh://git@github.com".insteadOf "https://github.com" || true
git config --global gc.auto 0 || true

if [ -e '/root/project/.git' ] ; then
  echo 'Fetching into existing repository'
  existing_repo='true'
  cd '/root/project'
  git remote set-url origin "$CIRCLE_REPOSITORY_URL" || true
else
  echo 'Cloning git repository'
  existing_repo='false'
  mkdir -p '/root/project'
  cd '/root/project'
  git clone --no-checkout "$CIRCLE_REPOSITORY_URL" .
fi

if [ "$existing_repo" = 'true' ] || [ 'false' = 'true' ]; then
  echo 'Fetching from remote repository'
  if [ -n "$CIRCLE_TAG" ]; then
    git fetch --force --tags origin
  else
    git fetch --force origin '+refs/heads/local_terraform:refs/remotes/origin/local_terraform'
  fi
fi

if [ -n "$CIRCLE_TAG" ]; then
  echo 'Checking out tag'
  git checkout --force "$CIRCLE_TAG"
  git reset --hard "$CIRCLE_SHA1"
else
  echo 'Checking out branch'
  git checkout --force -B "$CIRCLE_BRANCH" "$CIRCLE_SHA1"
  git --no-pager log --no-color -n 1 --format='HEAD is now at %h %s'
fi
```

**Comment by ideasculptor** [comment]
I was able to fix this by removing the /root/.gitconfig file that was added to recent images, and I confirmed that it was added between Feb 15 and Feb 17 of 2021, which was when the releases which bound the brokenness were released.  That .gitconfig file was overriding subsequent attempts to force git to use ssh by forcing git to use https instead.

**Comment by ChristophShyper** [comment]
Thank you for the feedback.

The way I'm using it at work is to mount separate `.gitconfig` in place of the one that is added to the image by default. Because it needs to contain token to access private repositories. As is suggested in the [README.md](https://github.com/devops-infra/docker-terragrunt#usage).
When I use it for personal projects I usually access only public repos and use that default file from the image.

Do you believe removing `.gitconfig` from the image and rely on additional config would be the best option?

**Comment by ChristophShyper** [comment]
@ideasculptor  After giving it some thought I agree it may be too bold to add default `.gitconfig`.
I've removed it and updated documentation to give the user option to decide how to handle git configuration.
In about 20 minutes version `aws-tf-0.14.10-tg-0.28.21` will have this change.
Sorry for the inconvenience.
