### ISSUE TITLE
Upgrade AWS cli version to v2?

### ISSUE THREAD

**Issue by ikarlashov** [devops-infra/docker-terragrunt#496]
Hi guys,

Just curios: is there any reason why are you sticking to branch **v1** for **aws cli**? Since `AWS CLI version 2, the latest major version of the AWS CLI, is now stable and recommended for general use.`

**Comment by ChristophShyper** [comment]
Hi! I must have missed when it started to be considered as trusted. 
There's busy week ahead of me and some holidays, so when I come back I'll try to add it to the image.

**Comment by ChristophShyper** [comment]
I had a look at v2 implementation. It's based on glibc, so it's not a standard for Alpine and would require a lot of hassle to add dependencies and installation.
Apparently, there are no plans to add it do some standard package management systems, like PyPi.
So I wouldn't assume it's a mature product yet, while v1 is updated almost daily.

I'll revise it in some time and see their progress to focus on Alpine, as it's a runner system for many CI/CD mechanisms and cannot imagine AWS would make it so terrible to install like GCP CLI.

**Comment by MattCWheeler** [comment]
AWS SSO support is only integrated into AWS CLI v2, not v1. Because we leverage AWS SSO for humans who sometimes need to run locally the same scripts that are run in CI, we strongly prefer AWS CLI v2 and so can't use this docker image without AWS CLI v2 support. Just wanted to make it clear that the impact here is significant due to the features that exist only in AWS CLI v2. Thanks!

**Comment by MattCWheeler** [comment]
@ChristophShyper would you be open to a pull request that attempts this? If so, would you rather see something based on actually sourcing https://github.com/Docker-Hub-frolvlad/docker-alpine-glibc/blob/master/Dockerfile, or an approach that does something very similar but inline, similar to this: https://stackoverflow.com/a/61268529? Either way, the idea is to bring glibc support in to alpine.

For my own use, I'm going to pursue the first option for now.

Thanks for this great repo.

**Comment by ChristophShyper** [comment]
Sure, I'm always open for a new PR. If you have an idea how to grasp it in a clean way then let's give it a try.
BTW, does AWS SSO work now in headless mode? I was trying it long ago and it wasn't possible via docker container.

**Comment by ChristophShyper** [comment]
Today I'll release version `tf-1.1.8-tg-0.36.6` which will have AWS CLI v2, but will be based now on Ubuntu, not Alpine.
