### ISSUE TITLE
GCP utilities not on $PATH

### ISSUE THREAD

**Issue by SmedbergM** [devops-infra/docker-terragrunt#509]
## `gcp` flavor needs `/google-cloud-sdk/bin` on its path

The `gcp` flavor installs the Google Cloud SDK during build; that SDK is written to `/google-cloud-sdk`. Additionally,
the installer writes the following to `/root/.profile`:
```sh
. /google-cloud-sdk/completion.bash.inc
. /google-cloud-sdk/path.bash.inc
```

However, the image does not actually source `/root/.profile` on startup, either in interactive:
```sh
$> docker run -it devopsinfra/docker-terragrunt:gcp-tf-1.0.9-tg-0.35.4 bash
bash-5.1# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
bash-5.1# source /root/.profile
bash-5.1# echo $PATH
/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
bash-5.1# 
```
or batch mode:
```sh
$> docker run devopsinfra/docker-terragrunt:gcp-tf-1.0.9-tg-0.35.4 gcloud --help
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "gcloud": executable file not found in $PATH: unknown.
```

This may be an issue affecting other flavors as well.

Note that since this profile file has 0640 permissions and is owned by `root`, it is not available when running the image as another user, which is also a less-than-ideal user experience.

### Possible solutions
- Add a `/root/.bashrc` file which _will_ be sourced by `bash`. This doesn't fix the issue for non-`root` users.
- Modify the image's `ENTRYPOINT`, either directly updating `PATH` or sourcing some common script before exec-ing the rest of the provided command. The entrypoint needs to be executable by all users, not just `root`.
- Create symlinks to all SDK executables inside `/usr/local/bin`.

## :warning: Checklist
* [x] Provided a clear and concise description of what the issue is.
* [x] Given a clear and concise description of what is expected.
* [x] Proposed a clear and concise description of any alternative solutions or other features.
* [x] Added any other context or screenshots about the feature request.
* [ ] Associated pull request has been already created and link was provided.

**Comment by ChristophShyper** [comment]
Hello. Sorry for not responding earlier, as was on a vacation. 
Honestly, I haven't used GCP CLI yet, only followed some documentation how to set it up.
Will have a look at it. Thank you for letting me know.

**Comment by ChristophShyper** [comment]
Thank you again @SmedbergM  for providing a good solution for this problem.
